import QRCode from 'qrcode';
import PDFDocument from 'pdfkit';
import crypto from 'crypto';
import { config } from '../config/env';
import { query, queryOne, withTransaction } from '../config/db';
import { saveBuffer } from './storageService';
import { createNotification, sendEmail } from './notificationService';
import { logAction } from './auditService';

// ─── Certificate Number ───────────────────────────────────────────────────────

export function generateCertificateNumber(): string {
  const year = new Date().getFullYear();
  const random = crypto.randomBytes(3).toString('hex').toUpperCase();
  return `MIVC-${year}-${random}`;
}

// ─── QR Code ─────────────────────────────────────────────────────────────────

export async function generateQRCode(certificateId: string): Promise<Buffer> {
  const url = `${config.qr.verifyBaseUrl}/${certificateId}`;
  return QRCode.toBuffer(url, { type: 'png', width: 200, margin: 2 });
}

// ─── PDF Certificate ──────────────────────────────────────────────────────────

interface CertificateParams {
  certificateNumber: string;
  certificateId: string;
  merchantName: string;
  businessName: string;
  instrumentTypeName: string;
  make?: string;
  model?: string;
  serialNumber?: string;
  operatingAddress: string;
  issueDate: string;
  expiryDate: string;
  qrBuffer: Buffer;
}

export async function generateCertificatePDF(params: CertificateParams): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width;
    const margin = 50;

    // ── Border ──
    doc.rect(margin - 10, margin - 10, pageWidth - (margin - 10) * 2, doc.page.height - (margin - 10) * 2)
      .stroke('#1d4ed8');

    // ── Header ──
    doc.fillColor('#1d4ed8').fontSize(22).font('Helvetica-Bold')
      .text('MIVC SYSTEM', { align: 'center' });
    doc.fontSize(10).fillColor('#4b5563')
      .text('Merchant Instrument Verification & Certification', { align: 'center' });
    doc.moveDown(0.5);

    doc.fillColor('#1d4ed8').fontSize(18).font('Helvetica-Bold')
      .text('INSTRUMENT VERIFICATION CERTIFICATE', { align: 'center' });
    doc.moveDown(0.3);

    // ── Divider ──
    doc.moveTo(margin, doc.y).lineTo(pageWidth - margin, doc.y).stroke('#1d4ed8');
    doc.moveDown(0.5);

    // ── Certificate Number ──
    doc.fillColor('#111827').fontSize(11).font('Helvetica-Bold')
      .text(`Certificate Number: `, { continued: true })
      .font('Helvetica').text(params.certificateNumber);
    doc.moveDown(0.5);

    // ── Details table ──
    const rows: [string, string][] = [
      ['Business Name', params.businessName],
      ['Owner / Contact', params.merchantName],
      ['Instrument Type', params.instrumentTypeName],
      ['Make / Model', [params.make, params.model].filter(Boolean).join(' / ') || 'N/A'],
      ['Serial Number', params.serialNumber || 'N/A'],
      ['Operating Address', params.operatingAddress],
      ['Issue Date', params.issueDate],
      ['Expiry Date', params.expiryDate],
    ];

    for (const [label, value] of rows) {
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#374151')
        .text(`${label}: `, { continued: true })
        .font('Helvetica').fillColor('#111827').text(value);
      doc.moveDown(0.3);
    }

    doc.moveDown(0.5);
    doc.moveTo(margin, doc.y).lineTo(pageWidth - margin, doc.y).stroke('#e5e7eb');
    doc.moveDown(0.5);

    // ── QR Code ──
    const qrSize = 120;
    const qrX = (pageWidth - qrSize) / 2;
    doc.image(params.qrBuffer, qrX, doc.y, { width: qrSize, height: qrSize });
    doc.moveDown(qrSize / doc.currentLineHeight() + 1);

    doc.fontSize(8).fillColor('#6b7280').font('Helvetica')
      .text('Scan QR code to verify authenticity', { align: 'center' });
    doc.moveDown(1);

    // ── Footer ──
    doc.moveTo(margin, doc.y).lineTo(pageWidth - margin, doc.y).stroke('#1d4ed8');
    doc.moveDown(0.3);
    doc.fontSize(8).fillColor('#6b7280')
      .text('This certificate is digitally generated by MIVC System. Verify authenticity at ' + config.qr.verifyBaseUrl, {
        align: 'center',
      });

    doc.end();
  });
}

// ─── Issue Certificate ────────────────────────────────────────────────────────

export async function issueCertificate(requestId: string, adminId: string): Promise<unknown> {
  // Fetch request + merchant + instrument type
  const requestRow = await queryOne<{
    id: string; merchant_id: string; instrument_type_id: string;
    make?: string; model?: string; serial_number?: string;
    operating_address_street: string; operating_address_city: string;
    operating_address_state: string; operating_address_pin: string;
    status: string;
    business_name: string; owner_name: string; merchant_email: string;
    instrument_type_name: string;
  }>(
    `SELECT r.*,
            m.business_name, m.owner_name, m.email AS merchant_email,
            it.name AS instrument_type_name
     FROM verification_requests r
     JOIN merchants m ON m.id = r.merchant_id
     JOIN instrument_types it ON it.id = r.instrument_type_id
     WHERE r.id = $1`,
    [requestId]
  );

  if (!requestRow) throw Object.assign(new Error('Request not found'), { status: 404 });
  if (requestRow.status !== 'inspected') {
    throw Object.assign(new Error('Request must be in inspected status to issue certificate'), { status: 400 });
  }

  const issueDate = new Date();
  const expiryDate = new Date(issueDate);
  expiryDate.setDate(expiryDate.getDate() + config.qr.certificateValidityDays);

  const certNumber = generateCertificateNumber();
  const certId = crypto.randomUUID();

  // Generate QR
  const qrBuffer = await generateQRCode(certId);
  const qrPath = await saveBuffer(qrBuffer, `qr-${certId}.png`);

  // Generate PDF
  const operatingAddress = [
    requestRow.operating_address_street,
    requestRow.operating_address_city,
    requestRow.operating_address_state,
    requestRow.operating_address_pin,
  ].filter(Boolean).join(', ');

  const pdfBuffer = await generateCertificatePDF({
    certificateNumber: certNumber,
    certificateId: certId,
    merchantName: requestRow.owner_name,
    businessName: requestRow.business_name,
    instrumentTypeName: requestRow.instrument_type_name,
    make: requestRow.make,
    model: requestRow.model,
    serialNumber: requestRow.serial_number,
    operatingAddress,
    issueDate: issueDate.toISOString().split('T')[0],
    expiryDate: expiryDate.toISOString().split('T')[0],
    qrBuffer,
  });

  const pdfPath = await saveBuffer(pdfBuffer, `cert-${certId}.pdf`);

  // Insert certificate
  const cert = await withTransaction(async (client) => {
    const [certRow] = (await client.query(
      `INSERT INTO certificates (id, certificate_number, request_id, merchant_id, issued_by_admin_id, issue_date, expiry_date, qr_code_path, pdf_path, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active')
       RETURNING *`,
      [certId, certNumber, requestId, requestRow.merchant_id, adminId,
       issueDate.toISOString().split('T')[0], expiryDate.toISOString().split('T')[0],
       qrPath, pdfPath]
    )).rows;

    await client.query(
      `UPDATE verification_requests SET status = 'certified', updated_at = NOW() WHERE id = $1`,
      [requestId]
    );

    return certRow;
  });

  // Notify merchant
  await createNotification(
    requestRow.merchant_id, 'merchant', 'certificate_issued',
    'Certificate Issued',
    `Your instrument verification certificate (${certNumber}) has been issued. Download it from your portal.`,
    'certificate', certId
  );

  await sendEmail(
    requestRow.merchant_email,
    `[MIVC] Certificate Issued — ${certNumber}`,
    `<h2>Certificate Issued</h2>
     <p>Dear ${requestRow.owner_name},</p>
     <p>Your instrument verification certificate <strong>${certNumber}</strong> has been issued.</p>
     <p>Log in to your Merchant Portal to download the certificate PDF.</p>
     <p>Certificate valid until: <strong>${expiryDate.toISOString().split('T')[0]}</strong></p>
     <p>Regards,<br/>MIVC System</p>`
  );

  await logAction({
    actorId: adminId,
    actorRole: 'admin',
    action: 'CERTIFICATE_ISSUED',
    entityType: 'certificate',
    entityId: certId,
    afterState: { certificateNumber: certNumber, requestId, merchantId: requestRow.merchant_id },
  });

  return cert;
}
